# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
    - command: >
        chmod +x *.sh &&
        export TZ='Asia/Taipei' && 
        source ~/.bashrc